services:
  laravel:
    container_name: pizzeri-php
    build: .
    volumes:
      - ./my-app:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pizzeri-db

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1



