services:
  nombre_app:
    container_name: nombre_app
    build: .
    volumes:
      - ./nombre_app:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - mysql

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nombre_base_datos
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1



