services:
  laravel:
    container_name: nombre_app
    build: .
    volumes:
      - ./nombre_app:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nombre_base_datos

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1



